spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8303
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost



