spring:
  application:
    name: eureka-service
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty= 0
server:
  port: 8302
zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://localhost:8300
    stock-service:
      path: /stock-service/**
      url: http://localhost:8301
    user-service:
      path: /user-service/**
      url: http://localhost:8303


